# SOPS configuration - defines which keys can encrypt/decrypt secrets
#
# IMPORTANT: Derive your age public key from the SSH host PRIVATE key:
#   sudo ssh-to-age -private-key -i /etc/ssh/ssh_host_ed25519_key | tail -1
#
# Or if sops-nix already generated a key:
#   sudo cat /var/lib/sops-nix/key.txt | grep "public key"
#
# Replace the placeholder below with your actual age public key

keys:
  # System age key (derived from SSH host private key)
  - &bluefin age18nl2k827fm6esp56a7vadd2lln3uww2j9vaaa2ads7z2zntppecqnpe92j
  - &laptop age1lxeguqlvkd75um6yd2hsum269p2zly6g7tgdeqxm602ujjurjyvqe9g24u
  - &server age1x6pwl6gwnrfmnjzu2kk9ave86tx9jur5yh870jzw94f8km7nm93shgfmqa
  - &desktop age15tmwsj524vlg5ppfx66zqf2jux5zk3sdw50jv708v7qzfr3vsq8q6f2ta3

  # Optional: Personal age key for editing secrets from any machine
  # Generate with: age-keygen -o ~/.config/sops/age/keys.txt
  # - &personal age1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *bluefin
          - *laptop
          - *server
          - *desktop
