name: Flake check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = nix-command flakes pipe-operators
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Enable aarch64 via QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Add aarch64 as extra platform
        run: |
          echo "extra-platforms = aarch64-linux" | \
          sudo tee -a /etc/nix/nix.conf
          sudo systemctl restart nix-daemon

      - name: Check flake
        run: nix flake check
