name: Mirror to Codeberg

on:
  push:
    branches: ["**"]
    workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: cssnr/mirror-repository-action@v1
        with:
          host: https://codeberg.org
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CODEBERG_TOKEN }}
          create: true
