name: Deploy Zensical to Pages

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "zensical.toml"
      - "mkdocs.yml"
      - "mkdocs.yaml"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/configure-pages@v6

      - uses: actions/checkout@v7

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.x"

      - run: pip install zensical

      - run: zensical build --clean

      - uses: actions/upload-pages-artifact@v5
        with:
          path: site

      - id: deployment
        uses: actions/deploy-pages@v5
